### ISSUE TITLE
About Entire project

### ISSUE THREAD

**Issue by dingzhexue** [dingzhexue/PACTGO#17]
I just have pushed my current work.
I implemented UI workflow as I can do.
As I mentioned yesterday, please contact the client and request a updated workflow so that I can implement all of them.
Please check and figure it out asap.
Thanks.

**Comment by smart-t17** [comment]
ok

**Comment by dingzhexue** [comment]
Hi
I fixed all the issues you suggested yesterday.
Please check it out and let me know.
Thanks.

**Comment by dingzhexue** [comment]
Hello!
How are you today?
I just have pushed the work of today.

Regards.

**Comment by smart-t17** [comment]
I'm waiting the design.
- find therapist page
- select date page
- select time page
- confirm page

**Comment by smart-t17** [comment]
![total](https://user-images.githubusercontent.com/33336058/45603495-05658980-ba5f-11e8-850a-92bf32ca8c7e.png)

**Comment by smart-t17** [comment]
NOTE: changed signup/login flow

**Comment by dingzhexue** [comment]
Hi
I just have pushed the current result.
All screens done.
I made some features of UI different with the current workflow due to incompatibility of UX.
It seems that the client is not so familiar to iOS app UX.
Please check it and let me know the result.
Regards.

**Comment by dingzhexue** [comment]
I just have fixed the existing issues.
I want you to request the global font file to your client.
Please check it and let me know the result.
Looking forward to hearing from you.
Thanks.

**Comment by dingzhexue** [comment]
_Hi
I just have fixed the font and ui issues.
Please check it out and let me know the result.
Regards._

**Comment by smartmaxdev** [comment]
I updated the client's feedback. Please mark per item if it is fixed.


> Hi
> I just have fixed the font and ui issues.
> Please check it out and let me know the result.
> Regards.

**Comment by smartmaxdev** [comment]
> I updated the client's feedback. Please mark per item if it is fixed.
> 
> > Hi
> > I just have fixed the font and ui issues.
> > Please check it out and let me know the result.
> > Regards.

**Comment by smart-t17** [comment]
I updated the client's feedback

**Comment by dingzhexue** [comment]
I just have pushed updated result. Please check it and reply for my comments.
Thanks.

**Comment by dingzhexue** [comment]
If the client is so strict, please request him to upload all the design to zeplin and specify all the pixels of buttons, labels, screens, images and etc. And to specify all the detail color codes.
