### ISSUE TITLE
navigationbar

### ISSUE THREAD

**Issue by smart-t17** [dingzhexue/PACTGO#18]

**Comment by smartmaxdev** [comment]
1. navigation bar background should fill the space.
actual: http://prntscr.com/kqworu
expected: http://prntscr.com/kqwpx0

**Comment by smart-t17** [comment]
2. navigation bar override the screen
step: 
1) go to my account
2) click appointment in the sidebar
actual: http://prntscr.com/kqwqlf
expected: navigation bar should not override the screen

**Comment by smart-t17** [comment]
3. default back button should be customized 
actual : http://prntscr.com/kqwusi
expected: back button should be matched the design
