### ISSUE TITLE
make sure the design is perfect

### ISSUE THREAD

**Issue by smart-t17** [dingzhexue/PACTGO#34]
we need to make everything design perfect before moving on. It’s really important. 
Font size, color, outlines, spacing
Please check psd font, size, color outlines, spacing.

**Comment by dingzhexue** [comment]
Please send me the font file so that I can add to xcode project.

**Comment by smart-t17** [comment]
[muli.zip](https://github.com/dingzhexue/PACTGO/files/2409451/muli.zip)

**Comment by smart-t17** [comment]
Please re check all screens - Font size, color, outlines, spacing, button size

**Comment by smart-t17** [comment]
http://prntscr.com/kz6elo

**Comment by smart-t17** [comment]
http://prntscr.com/kz6l5d

**Comment by smart-t17** [comment]
http://prntscr.com/kz6lqm

**Comment by smart-t17** [comment]
http://prntscr.com/kz6pty
My design was old, so I've just requested new design file. I'll upload it soon
The designer is offline. If you can do it without design, please update it

**Comment by smart-t17** [comment]
http://prntscr.com/kz6uud

**Comment by smart-t17** [comment]
http://prntscr.com/kz6v1z
Font needs to be bigger. 
And font lighter in color.

**Comment by smart-t17** [comment]
http://prntscr.com/kz728m

Everything is tight. Not to scale. 

The PERSONAL INFO needs to be spaced more

**Comment by smart-t17** [comment]
MY NOTE: Please mark like this if each item is fixed 
http://prntscr.com/kz7clg

**Comment by dingzhexue** [comment]
> http://prntscr.com/kz6pty
> My design was old, so I've just requested new design file. I'll upload it soon
> The designer is offline. If you can do it without design, please update it

Yeah, right. I will wait for the new design.

**Comment by dingzhexue** [comment]
> http://prntscr.com/kz6elo
The psd of 0923 should be changed?

**Comment by smart-t17** [comment]
> http://prntscr.com/kz728m
> 
> Everything is tight. Not to scale.
> 
> The PERSONAL INFO needs to be spaced more

This is not fixed. Please check design

**Comment by dingzhexue** [comment]
> > http://prntscr.com/kz728m
> > Everything is tight. Not to scale.
> > The PERSONAL INFO needs to be spaced more
> 
> This is not fixed. Please check design

This is the design. Is it true?
![design of accountpage](https://user-images.githubusercontent.com/1229815/46180680-9f56de80-c276-11e8-97ab-f1ec100d1951.PNG)
So do you want it?

**Comment by dingzhexue** [comment]
> http://prntscr.com/kz6elo

I don't understand what you want exactly.

**Comment by dingzhexue** [comment]
> http://prntscr.com/kz6uud

Please let me know exactly WHEN and WHERE this screen should be represented exactly.

**Comment by smart-t17** [comment]
https://prnt.sc/kzm5xq

**Comment by smart-t17** [comment]
http://prntscr.com/kzm68z
please check it using iphone 8 plus(simulator)

**Comment by smart-t17** [comment]
http://prntscr.com/kzm6k6

**Comment by smart-t17** [comment]
http://prntscr.com/kzm7gy
